      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python {version}
        uses: actions/setup-python@v5
        with:
          python-version: "{version}"

      - name: Install dependencies
        run: {install_cmd}

      - name: Build package
        run: |
          pip install build
          python -m build
