      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP {version}
        uses: shivammathur/setup-php@v2
        with:
          php-version: "{version}"

      - name: Install dependencies (production)
        run: composer install --no-interaction --no-dev --optimize-autoloader
